import type { ThemeDefinition } from "./types"

export const themes: ThemeDefinition[] = [
  {
    id: "midnight",
    name: "Midnight",
    description: "Blue accent on dark charcoal. Professional, trustworthy.",
    palette: {
      "--bg-primary": "#0A0A0B",
      "--bg-secondary": "#111113",
      "--bg-tertiary": "#1A1A1F",
      "--border": "#2A2A30",
      "--text-primary": "#EDEDEF",
      "--text-secondary": "#8A8A8E",
      "--text-tertiary": "#5A5A5E",
      "--accent": "#3B82F6",
      "--accent-hover": "#60A5FA",
      "--accent-muted": "#3B82F620",
      "--success": "#22C55E",
      "--warning": "#EAB308",
      "--error": "#EF4444",
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Emerald green on deep forest. Growth, freshness.",
    palette: {
      "--bg-primary": "#080C0A",
      "--bg-secondary": "#0F1512",
      "--bg-tertiary": "#17201B",
      "--border": "#243029",
      "--text-primary": "#E8F0EC",
      "--text-secondary": "#8A9B91",
      "--text-tertiary": "#5A6B61",
      "--accent": "#10B981",
      "--accent-hover": "#34D399",
      "--accent-muted": "#10B98120",
      "--success": "#22C55E",
      "--warning": "#EAB308",
      "--error": "#EF4444",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Amber warmth on dark earth. Creative, energetic.",
    palette: {
      "--bg-primary": "#0C0A08",
      "--bg-secondary": "#15120E",
      "--bg-tertiary": "#201C16",
      "--border": "#302A22",
      "--text-primary": "#F0ECE8",
      "--text-secondary": "#9B918A",
      "--text-tertiary": "#6B615A",
      "--accent": "#F59E0B",
      "--accent-hover": "#FBBF24",
      "--accent-muted": "#F59E0B20",
      "--success": "#22C55E",
      "--warning": "#F59E0B",
      "--error": "#EF4444",
    },
  },
  {
    id: "sakura",
    name: "Sakura",
    description: "Rose pink on plum shadow. Modern, distinctive.",
    palette: {
      "--bg-primary": "#0B090C",
      "--bg-secondary": "#131015",
      "--bg-tertiary": "#1C181F",
      "--border": "#2D2630",
      "--text-primary": "#F0ECF2",
      "--text-secondary": "#9B8A9E",
      "--text-tertiary": "#6B5A6E",
      "--accent": "#EC4899",
      "--accent-hover": "#F472B6",
      "--accent-muted": "#EC489920",
      "--success": "#22C55E",
      "--warning": "#EAB308",
      "--error": "#EF4444",
    },
  },
  {
    id: "nebula",
    name: "Nebula",
    description: "Violet glow on deep space. Creative, luxurious.",
    palette: {
      "--bg-primary": "#09080C",
      "--bg-secondary": "#100F15",
      "--bg-tertiary": "#18161F",
      "--border": "#262330",
      "--text-primary": "#EDECF2",
      "--text-secondary": "#8E8A9E",
      "--text-tertiary": "#5E5A6E",
      "--accent": "#8B5CF6",
      "--accent-hover": "#A78BFA",
      "--accent-muted": "#8B5CF620",
      "--success": "#22C55E",
      "--warning": "#EAB308",
      "--error": "#EF4444",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    description: "Crisp light with deep blue accent. Clean, professional.",
    palette: {
      "--bg-primary": "#F8FAFB",
      "--bg-secondary": "#EFF3F5",
      "--bg-tertiary": "#E4EAED",
      "--border": "#CBD5DA",
      "--text-primary": "#1A2028",
      "--text-secondary": "#4A5568",
      "--text-tertiary": "#718096",
      "--accent": "#2563EB",
      "--accent-hover": "#1D4ED8",
      "--accent-muted": "#2563EB18",
      "--success": "#16A34A",
      "--warning": "#CA8A04",
      "--error": "#DC2626",
    },
  },
  {
    id: "latte",
    name: "Latte",
    description: "Warm cream with terracotta accent. Earthy, inviting.",
    palette: {
      "--bg-primary": "#FAF6F1",
      "--bg-secondary": "#F0EAE2",
      "--bg-tertiary": "#E5DDD3",
      "--border": "#D1C4B4",
      "--text-primary": "#2D2013",
      "--text-secondary": "#6B5744",
      "--text-tertiary": "#8B7A68",
      "--accent": "#C2410C",
      "--accent-hover": "#9A3412",
      "--accent-muted": "#C2410C18",
      "--success": "#16A34A",
      "--warning": "#CA8A04",
      "--error": "#DC2626",
    },
  },
]

export const themesMap: Record<string, ThemeDefinition> = Object.fromEntries(
  themes.map((t) => [t.id, t])
)

export function getThemeById(id: string): ThemeDefinition | undefined {
  return themesMap[id.toLowerCase()]
}
